spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/movementsdb
    username: movementsuser
    password: movementspass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/finanzapp

server:
  port: 8082
  servlet:
    context-path: /movement


services:
  users:
    base-url: http://localhost:8085
  tags:
    base-url: http://localhost:8084
