parent=keycloak.v2
styles=css/styles.css
messages=messages
kcFormHeaderClass=fa-form-header
kcFormClass=fa-form
kcFormGroupClass=fa-form-group
kcLabelClass=fa-label
kcInputClass=fa-input
kcButtonClass=fa-btn
kcButtonPrimaryClass=fa-btn-primary
kcContentWrapperClass=fa-wrapper
kcHeaderClass=fa-header
kcLoginClass=fa-login
